[package]
name = "statics"
version = "0.4.0"
authors = ["Rasmus Kaj <rasmus@krats.se>"]
edition = "2018"

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["mime03"] }

[dependencies]
mime = "0.3.0"
