language: rust
rust:
  - stable
  - 1.34.2
  - 1.32.0
  - 1.31.1
  - beta
  - nightly
matrix:
  include:
   - rust: stable
     env: TASK=rustfmt
     before_script:
      - rustup component add rustfmt
     script:
      - cargo fmt -- --check
      - cd examples/actix && cargo fmt -- --check
      - cd ../gotham && cargo fmt -- --check
      - cd ../iron && cargo fmt -- --check
      - cd ../nickel && cargo fmt -- --check
      - cd ../simple && cargo fmt -- --check
      - cd ../static-sass && cargo fmt -- --check
      - cd ../statics && cargo fmt -- --check
      - cd ../warp && cargo fmt -- --check
   - rust: stable
     env: EXAMPLE=ed2018
     script: cd examples/$EXAMPLE && cargo test
   - rust: stable
     env: EXAMPLE=static-sass
     script: cd examples/$EXAMPLE && cargo test
   - rust: stable
     env: EXAMPLE=actix
     script: cd examples/$EXAMPLE && cargo test
   - rust: stable
     env: EXAMPLE=warp
     script: cd examples/$EXAMPLE && cargo test
   - rust: stable
     env: EXAMPLE=gotham
     script: cd examples/$EXAMPLE && cargo test
   - rust: stable
     env: EXAMPLE=nickel
     script: cd examples/$EXAMPLE && cargo test
   - rust: stable
     env: EXAMPLE=iron
     script: cd examples/$EXAMPLE && cargo test
  allow_failures:
    - rust: nightly
      env:
script:
 - cargo build
 - cargo test
 - cd examples/simple && cargo test
 - cd ../statics && cargo test
