# Define jobs for testing ructe

on: [push, pull_request]

name: CI

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.75.0
          - 1.67.1
          - 1.65.0
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  examples:
    name: Test example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - actix
          - axum
          - gotham
          - simple
          - static-sass
          - statics
          - tide
          - warp03
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"

      - name: Check format
        run: |
          cd examples/${{ matrix.example }}
          cargo fmt -- --check

      - name: Run test
        run: |
          cd examples/${{ matrix.example }}
          cargo test
